version: 2.0
jobs:
  build:
    docker:
      - image: klembara/swift4:0.0.1
    steps:
      - checkout

  test:
    docker:
      - image: klembara/swift4:0.0.1
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
           swift package fetch
           swift test -c release

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
